kind = "mobile"
previewPath = "/"
title = "AG Mart"
version = "1.0.0"
id = "artifacts/ag-mart"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 18371

[services.development]
run = "pnpm --filter @workspace/ag-mart run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ag-mart", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/ag-mart", "run", "serve" ]

[services.env]
PORT = "18371"
BASE_PATH = "/"
